### ISSUE TITLE
Secrets are not hidden if provisioner fails

### ISSUE THREAD

**Issue by Alan-Hinton** [hashicorp/terraform-provider-null#108]
### Terraform CLI and Provider Versions

Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.18.0
+ provider registry.terraform.io/hashicorp/azurerm v2.95.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Terraform Configuration

```terraform
resource "random_password" "password" {
  length      = 16
  special     = false
  lower       = true
  number      = true
  upper       = true
  min_lower   = 1
  min_numeric = 1
  min_upper   = 1
}

resource "null_resource" "sql_login" {

  triggers = {
    always_run = timestamp()
  }

  provisioner "local-exec" {
    command     = <<EOT
      ${path.module}/scripts/AddSqlLogin.ps1 `
        -SqlServerName "${var.sql_server_name}" `
        -AdminUserName "${var.admin_username}" `
        -AdminPassword "${var.admin_password}" `
        -LoginName "${var.login_name}" `
        -LoginPassword "${random_password.password.result}"
    EOT
    interpreter = ["powershell", "-Command"]
  }
}
```

### Expected Behavior

If the script AddSqlLogin.ps1 cannot be found I should get an error telling me it cannot be found.  Any secrets in the error should be overwritten with stars '*'.

### Actual Behavior

I get the following error, with the passwords visible :
╷
│ Error: local-exec provisioner error
│ 
│   with module.server_logins["APIuser"].null_resource.sql_login,
│   on smart-infrastructure-terraform-modules/common_modules/azure/databases/pwsh_sql_server_login/main.tf line 19, in resource "null_resource" "sql_login":
│   19:   provisioner "local-exec" ***
│ 
│ Error running command '
│ smart-infrastructure-terraform-modules/common_modules/azure/databases/pwsh_sql_server_login/scripts/AddSqlLogin.ps1
│ `
│         -SqlServerName "reliability-staging-global.database.windows.net" `
│         -AdminUserName "smart_admin" `
│         -AdminPassword "<actual password was visible here>" `
│         -LoginName "APIuser" `
│         -LoginPassword "<actual password was visible here>"
│ ': exec: "powershell": executable file not found in $PATH. Output: 

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

Low

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bflad** [comment]
Hi @Alan-Hinton 👋  Thank you for raising this and sorry you ran into trouble here. In Terraform, the provisioner functionality is wholly managed by [Terraform CLI](https://github.com/hashicorp/terraform), not any provider resource configurations which might contain them.

It turns out, a similar issue report was filed upstream regarding provisioners and sensitive values: https://github.com/hashicorp/terraform/issues/30633

My suggestion would be to subscribe to that issue and potentially add a 👍  reaction to stay up to date with the latest discussions on it. Since there is nothing we can do to change this behavior in this (or any provider), I'm going to close this out. Thanks again for raising this though!
