### ISSUE TITLE
Terraform framework change

### ISSUE THREAD

**Issue by lorodoes** [hashicorp/terraform-provider-null#156]
### Terraform CLI and Provider Versions

The terraform null provider 3.2.0 is causing issues when upgrading from 0.11 to 0.12. 
Exception Error in plan -
Error: Unable to Read Previously Saved State for UpgradeResourceState

There was an error reading the saved resource state using the current resource
schema.

If this resource state was last refreshed with Terraform CLI 0.11 and earlier,
it must be refreshed or applied with an older provider version first. If you
manually modified the resource state, you will need to manually modify it to
match the current resource schema. Otherwise, please report this to the
provider developer:

flatmap states cannot be unmarshaled, only states written by Terraform 0.12
and higher can be unmarshaled

With the 3.1.1 provider this didn't occur. I had the null provider pinned to all 3.0.0 versions since I didn't realize that changing the framework would be considered a minor change rather than a major change. 

### Terraform Configuration

```terraform
resource "null_resource" "notification" {
  count = var.multi_region == false ? 1 : 0
  triggers = {
    crit = module.aws-cams-pagerduty.pagerduty_service_integration_Critical_integration_key
    warn = module.aws-cams-pagerduty.pagerduty_service_integration_Warning_integration_key
    back = module.aws-cams-pagerduty.pagerduty_service_integration_Backup_integration_key
    secu = module.aws-cams-pagerduty.pagerduty_service_integration_Security_integration_key
    ctop = module.aws-cams-notification-primary.aws_sns_topic_CMSCriticalAlarmTriggeredTopic
    wtop = module.aws-cams-notification-primary.aws_sns_topic_CMSWarningAlarmTriggeredTopic
  }
}
```

### Expected Behavior

3.2.0 should be able to upgrade a 0.11 statefile

### Actual Behavior

Throws error

Exception Error in plan -
Error: Unable to Read Previously Saved State for UpgradeResourceState

There was an error reading the saved resource state using the current resource
schema.

If this resource state was last refreshed with Terraform CLI 0.11 and earlier,
it must be refreshed or applied with an older provider version first. If you
manually modified the resource state, you will need to manually modify it to
match the current resource schema. Otherwise, please report this to the
provider developer:

flatmap states cannot be unmarshaled, only states written by Terraform 0.12
and higher can be unmarshaled

### Steps to Reproduce

1. have statefile of 0.11
2. attempt to upgrade a statefile that is using the null provider from 0.11 to 0.12
3. terraform plan
4. fail

### How much impact is this issue causing?

Low

### Additional Information

I know this can't be fixed with the new framework, but I would contend that the framework change should be consider a major change not a minor.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bookshelfdave** [comment]
Hello @lorodoes - thanks for reporting this issue.

Unfortunately, we no longer support Terraform v0.11 with the null provider. Some details on this decision are located on [a 2019 blog entry](https://www.hashicorp.com/blog/deprecating-terraform-0-11-support-in-terraform-providers), as well as the null provider [changelog from October 8 2020](https://github.com/hashicorp/terraform-provider-null/blob/main/CHANGELOG.md#300-october-08-2020).

The error is raised because the state was not refreshed with Terraform 0.12 and later, so it still has the old Terraform 0.11 state from whenever it was applied with some older version of the provider that supported Terraform 0.11

You may be able to get out of this situation by temporarily pinning to the older version of the provider and running terraform refresh (or terraform apply).

If you uncover any other issues related to the null provider, please feel free to report them on this repo, and we'll take a look.
