### ISSUE TITLE
Move docs directory structure to standard with /d/ and /r/

### ISSUE THREAD

**Issue by brandonjbjelland** [hashicorp/terraform-provider-null#17]
### Terraform Version

N/A

### Affected Resource(s)

`data "null_data_source"` and `resource "null_resource"`

### Core issue

I've built a [vscode extension](https://github.com/run-at-scale/vscode-terraform-doc-snippets) ([here on the marketplace](https://marketplace.visualstudio.com/items?itemName=run-at-scale.terraform-doc-snippets)) to pull code examples on each data source and resource from `website/docs/r` and `website/docs/d` of each public provider in this organization. This provider as well as `http`, `external`, and `scaffolding` all have documentation in the `website/docs/` root which will make for ugly code on my end to accommodate these outliers. Is there a good reason these provider repos are structured differently? With a go ahead to move them to the standard directory structure, I'd be happy to own the PR for getting these final repos in line with the others.

Let me know if you see any issue with me shuffling the files around into directories. Thanks!

**Comment by brandoconnor** [comment]
Bump! C'mon HashiCorp, you're better than letting issues slide.

**Comment by bflad** [comment]
Thank you for raising this awhile ago, @brandonjbjelland 👍 

It appears this issue is no longer relevant after https://github.com/hashicorp/terraform-provider-null/pull/54 happened, so in that regard I'm going to close this issue.

To provide some additional context since this issue is older now, provider developers currently have two conventional options with the Terraform Registry hosting the documentation that they _must_ follow:

- "Legacy" structure: `website/docs/(d|r)`
- "New" structure: `docs/(data-sources|resources)`

Registry documentation on this can be found here: https://www.terraform.io/registry/providers/docs

Hope this helps.
